# serverless.yml
service: aws-lambda-people
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  timeout: 20

custom:
  dotenv:
    path: .env
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION_NAME

functions:
  getAllBySwapi:
    handler: src/index.handler
    events:
      - http:
          path: /people/swapi
          method: get

  getAll:
    handler: src/index.handler
    events:
      - http:
          path: /people/all
          method: get

  create:
    handler: src/index.handler
    events:
      - http:
          path: /people
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
