openapi: 3.0.3
swagger: 3
info:
  title: PEOPLE API
  version: '1.0.0'
  description: API used for people management.
  contact:
    email: svencooof@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  tags:
    - name: people
schemes:
  - 'https'

paths:
  /people/swapi:
    get:
      tags:
        - PeopleSwapi
      summary: Get all peoples of star wars from swapi
      description: This endpoint get all peoples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/PeopleSwapiResponse'

  /people:
    get:
      tags:
        - People
      summary: Get all peoples of database
      description: This endpoint get all peoples
      responses:
      '200':
        description: Successful operation
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/PeopleResponse'
                total:
                  type: number
                  example: 1
                page:
                  type: number
                  example: 1
                take:
                  type: number
                  example: 1
                totalPage:
                  type: number
                  example: 1

    post:
      tags:
        - People
      summary: Create a people in database
      description: This endpoint create people
      consumes:
        - application/json
      parameters:
        - in: body
          name: create
          description: payload to create
          schema:
            type: object
            properties:
              name:
                type: string
                required: true
              height:
                type: integer
                required: true
              mass:
                type: integer
                required: true
              hairColor:
                type: string
                required: true
              skinColor:
                type: string
                required: true
              eyeColor:
                type: string
                required: true
              birthYear:
                type: string
                required: true
              gender:
                type: string
                required: true
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    PeopleSwapiResponse:
      type: object
      properties:
        nombre:
          type: string
        altura:
          type: integer
        masa:
          type: integer
        colorPelo:
          type: string
        colorPiel:
          type: string
        colorOjo:
          type: string
        aniversario:
          type: string
        genero:
          type: string
        fechaFundado:
          type: string

    PeopleResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        height:
          type: integer
        mass:
          type: integer
        hairColor:
          type: string
        skinColor:
          type: string
        eyeColor:
          type: string
        birthYear:
          type: string
        gender:
          type: string
        createdAt:
          type: string
